server:
    port: 8080

spring:
    cloud:
        gateway:
            server:
                webflux:
                    routes:
                        - id: book-service
                          uri: http://localhost:8081
                          predicates:
                            - Path=/api/books/**
                          filters:
                            - name: CacheRequestBody
                              args:
                                bodyClass: java.lang.String
    application:
        name: testday1gw
